[tool.poetry]
name = "inferactively-pymdp"
version = "1.0.0"
description = "A Python package for solving Markov Decision Processes with Active Inference"
authors = ["Conor Heins <conor.heins@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include="pymdp"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.19.5"
jax = "^0.4"
jaxlib = "^0.4"
jaxtyping = "^0.2"
equinox = "^0.11"
multimethod = "^1.11"
matplotlib= "3.1.3"
seaborn = "^0.11.1"
mctx = "^0.0.5"
networkx = "^3.3"

[tool.poetry.group.test.dependencies]
pytest = "^6.0.0"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
